### ISSUE TITLE
Wrong syntax in "items.xml" of the "SNJ - FoodAddOn" mod

### ISSUE THREAD

**Issue by theloser** [Techgeek20/7D2D-V1_Aircraft_Carrier_Challenge#6]
Modpack: [DEV-07282024_111900_V1(b333)](https://github.com/Techgeek20/7D2D-V1_Aircraft_Carrier_Challenge/releases/tag/DEV-07282024_111900_V1(b333))
Tested with V1.1 (b14) and with V1.0 (b336), as Steam doesn't let me download V1.0 (b333) anymore

When starting/loading the game, several "Parent folder not found" errors happen:

```
2024-11-10T15:09:16 39.894 ERR Loading AssetBundle "D:/Games/Steam/steamapps/common/7 Days To Die/7DaysToDie_Data/../Data/Bundles/Standalone/Other/Items" failed: Parent folder not found!
2024-11-10T15:09:16 39.894 ERR Loading AssetBundle "D:/Games/Steam/steamapps/common/7 Days To Die/7DaysToDie_Data/../Data/Bundles/Standalone/Other/Items" failed: Parent folder not found!
...
```

This is because the `items.xml` file of the `SNJ - FoodAddOn` mod contains a wrong syntax. This is what it looks like in the downloaded modpack:

```
<property name="Meshfile" value="#Other/Items?Food/bottled_waterPrefab.prefab"/>
<property name="DropMeshfile" value="#Other/Items?Misc/sack_droppedPrefab.prefab"/>
```

And this is what it should look like:

```
<property name="Meshfile" value="@Other/Items/Food/bottled_waterPrefab.prefab"/>
<property name="DropMeshfile" value="@Other/Items/Misc/sack_droppedPrefab.prefab"/>
```

After replacing `#Other` with `@Other` and `Items?` with `Items/` in this file the errors are gone.

**Comment by Techgeek20** [comment]
Modlet removed after internal testing and running into other issues with the modlet. New release tag created this morning.
