### ISSUE TITLE
Duplicate recipes

### ISSUE THREAD

**Issue by theloser** [Techgeek20/7D2D-V1_Aircraft_Carrier_Challenge#8]
Modpack tested: [MAIN - 11102024_0937](https://github.com/Techgeek20/7D2D-V1_Aircraft_Carrier_Challenge/releases/tag/Main-1.1b14-11102024_0937)

Some recipes appear more than once:
- Stone Arrow to Stone Crossbow bolt (and vice versa)
- Iran Arrow to Iron Crossbow bolt (and vice versa)

That's because those recipes are defined in `.\Aircraft carrier Challenge\Config\recipes.xml`
as well as in `.\Techs_Boom-Booms_Pack_XMLOnly\Config\recipes.xml`.

Removing the recipes from either file fixes it.

**Comment by Techgeek20** [comment]
Fixed.  The Boom-Booms pack is an optional modlet that can be "dropped" into other packs and then would provide the conversion recipes.

**Comment by theloser** [comment]
With change https://github.com/Techgeek20/7D2D-V1_Aircraft_Carrier_Challenge/compare/Main-1.1b14-11102024_0937...Main-1.1b14-11112024_1756 you also removed recipes for...

- ammoArrowSteelAP <--> ammoCrossbowBoltSteelAP
- ammoArrowFlaming <--> ammoCrossbowBoltFlaming
- ammoArrowExploding <--> ammoCrossbowBoltExploding

... which weren't duplicates -- unless you did remove those recipes intentionally ;-)
